### ISSUE TITLE
Build fails on gcc-10

### ISSUE THREAD

**Issue by dkogan** [rocky/remake#109]
Hi. The latest 4.3-dbg1.5 release doesn't build with gcc-10:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=957756

This report is for the previous release, but the issue is there in the latest release too. The problem is that remake is defining global variables in header files, which creates multiple symbols (one for each object built from a .c that #includes such a header), and those symbols clash. gcc-10 changed the default build flags, which trigger the failure. The legacy mode can be enabled with -fcommon or we can not define globals in headers. This is the first issue described in the porting guide:

https://gcc.gnu.org/gcc-10/porting_to.html

Thanks

**Comment by rocky** [comment]
Ok. Thanks for the report. I'll installing gcc-10 and looking at soon.

**Comment by trofi** [comment]
Looks like the fix does not apply cleanly to latest 4.3 release.

What do you think of cutting `gcc-10` compatible release for `remake`?

**Comment by rocky** [comment]
Patches are welcome.

**Comment by trofi** [comment]
Can you clarify what patch you expect? AFAIU 08113a2 is already in `master` branch, but no `remake` releases contain it.

**Comment by rocky** [comment]
Ah - my misunderstanding. Sure I'll update the 4.3 release with this and the more recent changes when I get a chance.

**Comment by rocky** [comment]
Ok - released.

**Comment by trofi** [comment]
Thank you! Proposed update downstream as https://github.com/NixOS/nixpkgs/pull/156290
