### ISSUE TITLE
Failing to run tests

### ISSUE THREAD

**Issue by SCOTT-HAMILTON** [rocky/remake#117]
Hello, I'm updating the remake package of NixOS and a good practice is to run as much tests as possible, especially those provided by the package. So I tried to run make check but I get the following error : 

```
variables/INCLUDE_DIRS .................................. FAILED (1/2 passed)
[...]

1 Test in 1 Category Failed (See .diff* files in work dir for details) :-(

```

And the diff file content `tests/work/variables/INCLUDE_DIRS.diff`  is : 
```
*** work/variables/INCLUDE_DIRS.base	Sat Apr 17 17:51:23 2021
--- work/variables/INCLUDE_DIRS.log	Sat Apr 17 17:51:23 2021
***************
*** 0 ****
--- 1 ----
+ work/variables/INCLUDE_DIRS.mk:3: .INCLUDE_DIRS is empty
```

**Comment by rocky** [comment]
The same test is run on MacOS and and Ubuntu. See https://travis-ci.org/github/rocky/remake/builds/738502192 for example. So it is possible that there is a problem with this test on NixOS. 

This test comes from GNU Make, and some of their tests are flaky. Does the equivalent version of GNU Make succeed?

**Comment by SCOTT-HAMILTON** [comment]
I have the same issue with GNU Make

**Comment by rocky** [comment]
Ok. Since we are compatible with GNU Make this isn't a bug, but a compatability feature.
