### ISSUE TITLE
Clarification concerning the message file 'all' does not exist

### ISSUE THREAD

**Issue by Lecrapouille** [rocky/remake#131]
Hi! This is not a bug but something disturbing me and maybe documentation could be upgraded. My makefile has a `all:` rule with `PHONY` keyword.

```
.PHONY: all
all: xxx
```

When doing: `remake -x all` I see this message
```
File 'all' does not exist.
```

Like in your animated gifs in your README. But since I had PHONY, the `all` rule should not be considered as a file but as a command, right ? This message is disturbing.

**Comment by rocky** [comment]
Possibly disturbing but this is the way GNU Make and other Make's work.  It is a feature not a bug.
