### ISSUE TITLE
Latest release tag older than previous

### ISSUE THREAD

**Issue by alerque** [rocky/remake#133]
Is the new release tag a typo? It seems like 3.4 is a step back from 4.3.

**Comment by rocky** [comment]
Yes, you are correct, I am dyslexic.

I got the release name wrong in publishing the release on github. The tarball name and the [folder/files on sourceforge](https://sourceforge.net/projects/bashdb/files/remake/4.3%2Bdbg-1.6/) were correct. 

I've corrected the github release and should have removed the erroneous release. But please double check.

**Comment by alerque** [comment]
Looks better now. Arch Linux packaging updated…
