### ISSUE TITLE
Tutorial Video #2 missing

### ISSUE THREAD

**Issue by MrLinear** [rocky/remake#14]
I went to:

http://showmedo.com/videotutorials/video?name=linuxBernsteinMakeDebug1&fromSeriesID=40

to watch the tutorial videos and it appears tutorial video #2 is missing. Is this video still available? If so, where can I find it?

**Comment by rocky** [comment]
See https://vimeo.com/97397484  It was also listed via the wiki, but I've just changed that to make it more clear that this is the 2nd part of the demo.

**Comment by MrLinear** [comment]
You may want to update this page:

http://bashdb.sourceforge.net/remake/

which points to showmedo and the missing video.

**Comment by rocky** [comment]
Ok, done. Thanks. 

And you may want to update your rating of this project on github ;-)

**Comment by MrLinear** [comment]
Done
