### ISSUE TITLE
Add remake --graph to show dependency graph

### ISSUE THREAD

**Issue by sheijk** [rocky/remake#15]
It would be very cool to be able to visualise all dependencies/prerequisites of a makefile. For example a ---graph switch which outputs a graphviz/dot file. There are a few perl scripts trying to do this but they fail for complex makefiles for me (which are the ones where it's needed the most). There is a make-profiler project which has this but unfortunately the project seems to be dormant so it would be cool if remake could adapt this feature (see https://github.com/eddyp/make-profiler).

**Comment by rocky** [comment]
Seems like a cool idea.

I'll be out of busy the next couple of weeks and even out of town, so for now it has to wait. However if you are anyone else is up for it by all means fork this code pull in changes from that and make a pull request.

**Comment by rocky** [comment]
BTW when I tried using the --graph option in one of the make-profiler branches by running make on itself,  the output I saw in svg was pretty useless. So I have a feeling more work to that code will be needed.

**Comment by rocky** [comment]
In the *profile* branch, is some code that attempts to produce callgrind-style data. 

If you can, feel free to help out. (After all, *you* may want or need this more than I do.)

It does something, although I don't think it's very good. Part of the problem is understanding the output format I need to produce for callgrind. So just creating some simple examples and figuring out what the callgrind output should be would probably be helpful. And of course if you want to fix the C code that'd be cool too. The file that does this is profile.c; it's pretty simple. It hooks into main.c and job.c and that's pretty simple.

**Comment by rocky** [comment]
With commit 93694ad I think it's all pretty much there. Try it out. (I'll assume lack of feedback or interest means this is solved.)

**Comment by sheijk** [comment]
That was faster than expected. Very cool, thanks. I'm trying to test this but I can't get it to work due to issues with autoreconf (on OS X, using homebrew, autoconf version 2.69, automake 1.15). I think this is an issue with my local installation, though. Is there another way to get the configure script?

**Comment by rocky** [comment]
You can get a tarball from https://sourceforge.net/projects/bashdb/files/remake/4.1%2Bdbg-1.0/

**Comment by sheijk** [comment]
Ok, that one builds. I can now call remake --profile to get a callgrind file. But --graph is not accepted and the commit above seems to only refer to profile. So is --graph not there?

**Comment by rocky** [comment]
`--profile` does both target timing and target-dependency graphing. That's the way the callgrind format works. See 
https://gist.github.com/rocky/e946f17fc701ceb611af#file-kcachegrind-remake-png for some sample output.

**Comment by sheijk** [comment]
I see. I can now generate nice graphs using gprof2dot. Thanks a lot!

**Comment by rocky** [comment]
I actually prefer the dot graph produced inside kcachegrind when it exports the graph over what gprof2dot gives. See https://gist.github.com/rocky/e946f17fc701ceb611af#file-callgraph-dot-pdf 

However I don't know what magic kcachegrind uses; I assume it's just calling dot with different parameters.

**Comment by rocky** [comment]
> I see. I can now generate nice graphs using gprof2dot. Thanks a lot!

You are welcome; remember to star the project so that others will be more likely find find this.
