### ISSUE TITLE
problem building on Ubuntu 14.04.2 LTS

### ISSUE THREAD

**Issue by mwoodpatrick** [rocky/remake#16]
Trying to build on Ubuntu 14.04.2 LTS fails when building docs (I do have texinfo installed)

    Making all in doc
make[2]: Entering directory `/home/scratch.mwoodpatrick/remake/doc'
restore=: && backupdir=".am$$" && \
        am__cwd=`pwd` && CDPATH="${ZSH_VERSION+.}:" && cd . && \
        rm -rf $backupdir && mkdir $backupdir && \
        if (/bin/bash /home/scratch.mwoodpatrick/remake/config/missing makeinfo --version) >/dev/null 2>&1; then \
          for f in make.info make.info-[0-9] make.info-[0-9][0-9] make.i[0-9] make.i[0-9][0-9]; do \
            if test -f $f; then mv $f $backupdir; restore=mv; else :; fi; \
          done; \
        else :; fi && \
        cd "$am__cwd"; \
        if /bin/bash /home/scratch.mwoodpatrick/remake/config/missing makeinfo   -I . \
         -o make.info make.texi; \
        then \
          rc=0; \
          CDPATH="${ZSH_VERSION+.}:" && cd .; \
        else \
          rc=$?; \
          CDPATH="${ZSH_VERSION+.}:" && cd . && \
          $restore $backupdir/* `echo "./make.info" | sed 's|[^/]*$||'`; \
        fi; \
        rm -rf $backupdir; exit $rc
make.texi:5: @include: could not find version.texi
make.texi:24: warning: undefined flag: UPDATED
make.texi:25: warning: undefined flag: VERSION
make.texi:63: warning: undefined flag: VERSION
make.texi:64: warning: undefined flag: UPDATED-MONTH
make[2]: *** [make.info] Error 1
make[2]: Leaving directory `/home/scratch.mwoodpatrick/remake/doc'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/scratch.mwoodpatrick/remake'
make: *** [all] Error 2

**Comment by rocky** [comment]
Try this:

    $ cd doc
    $ make stamp-vti
    Updating ./version.texi

Yeah, this is a weirdness of the automake system and how it interacts for texinfo. I don't understand why it is the way it is, and it's that way in GNU make as well as best as I can tell.

**Comment by mwoodpatrick** [comment]
Yes that worked many thanks much appreciated
