### ISSUE TITLE
Build error: "could not find version.texi"

### ISSUE THREAD

**Issue by deborasetton** [rocky/remake#20]
Hi,

I was trying to build remake following the instructions on the README.md file and the `make` command was failing with the following error (some lines omitted for brevity):

```
make.texi:5: @include: could not find version.texi
Makefile:388: recipe for target 'make.info' failed
make[2]: *** [make.info] Error 1
Makefile:879: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
Makefile:599: recipe for target 'all' failed
make: *** [all] Error 2
```

I eventually got it to work by running, before `make`, `cd doc && make stamp-vti`, which I found in travis.yml.

I don't know if I was doing something wrong, but thought I'd give a heads up about this, in case other people run into the same issue.

Thanks!

**Comment by rocky** [comment]
Yeah, this is basically the same thing as #16 .  Do me a favor and add something to the [wiki]( https://github.com/rocky/remake/wiki). 

If someone has a good solution for this, I'm cool with that too. There is a commented-out dependency in the Makefile, but I'm not sure why that's commented out or if uncommenting it will help.

**Comment by rocky** [comment]
Nevermind.  I've just changed the code to not build the info files if `--maintainer-mode` isn't set. I think this will be the least hassle for most people who build from git.

If this works for you, close the issue.

**Comment by deborasetton** [comment]
Ok, thank you. Closing the issue.
