### ISSUE TITLE
print all variables on error

### ISSUE THREAD

**Issue by rofl0r** [rocky/remake#30]
i've searched for this feature but to no avail.
is it implemented?

**Comment by rocky** [comment]
I don't think its there. You can however --debug=error which will put you in a debugger on error and then run 'info variables'.

**Comment by rofl0r** [comment]
it seems the --debug=error functionality is new (not in the 3.82 release).
the "info variables" is very helpful though, thanks for the tip

**Comment by rocky** [comment]
If there are improvements in newer releases and _you_ are willing to do the backport, I'm amenable to including them that branch.

**Comment by rofl0r** [comment]
can you point me to the commit that added the functionality?

**Comment by rocky** [comment]
bfeb13c67caf60c79630f5f99dd4eea061542751
