### ISSUE TITLE
archive test failures in remake 4.1-dbg1.1

### ISSUE THREAD

**Issue by dkogan** [rocky/remake#31]
Hi.

I'm seeing persistent test suite errors in the archive test. I'm at
remake-4.1+dbg-1.1:

     dima@shorty:~/debianstuff/remake/tests$ git describe --tags
     release-remake-4.1+dbg-1.1

Recipe:

1. autoreconf -f -i

2. ./configure --disable-nls

3. make

4. cd tests/; ./run_make_tests -make ../make features/archives

     dima@shorty:~/debianstuff/remake/tests$ ./run_make_tests -make ../make features/archives
     ------------------------------------------------------------------------------
                Running tests for GNU make on Linux shorty 4.6.1 x86_64
                                  GNU Make 4.1+dbg1.0
     ------------------------------------------------------------------------------

     Clearing work...
     Making work dirs...

     features/archives ....................................... FAILED (3/10 passed)

     7 Tests in 1 Category Failed (See .diff* files in work dir for details) :-(

I can give you the differences, but first I'd like to confirm that this is
working for you. I'm on a fairly vanilla Debian/sid box.

Thanks

**Comment by rocky** [comment]
I couldn't find a 4.6 kernel from vagrant http://www.vagrantbox.es/ but I did try on sid on a 3.16 kernel and features/archies passes fine. 

Please see if an unmodified GNU make 4.1 passes the features test. There's nothing in the remake patches that I recall around changing how archives works.

**Comment by dkogan** [comment]
R. Bernstein <notifications@github.com> writes:

> I couldn't find a 4.6 kernel from vagrant http://www.vagrantbox.es/
> but I did try on sid on a 3.16 kernel and features/archies passes
> fine.
>
> Please see if an unmodified GNU make 4.1 passes the features test.
> There's nothing in the remake patches that I recall around changing
> how archives works.

Thanks for checking. I'll run some experiments on my end.

**Comment by dkogan** [comment]
Hi. This is a Debian-specific failure (that you should have seen; your sid probably was too old). In any case, the Debian make package has a patch for the test suite:

https://anonscm.debian.org/git/users/srivasta/debian/make-dfsg.git/commit/?id=dbcb58

I'll do the same for remake.
