### ISSUE TITLE
The remake >= 4.0 tags all have the non-remake manpage

### ISSUE THREAD

**Issue by dkogan** [rocky/remake#32]
The make.1 manpage file in the recent tags is from GNU Make, without the remake-specific functionality described

**Comment by rocky** [comment]
Patches are welcome.

**Comment by dkogan** [comment]
https://github.com/dkogan/remake/commit/d99b55a8a8c64cc24c07b09c5d772a238f692ade

**Comment by dkogan** [comment]
The above commit applies the difference between make-3.82 and remake-3.82, and removes reference to the make-4.1 --trace option, which I presume has been taken over by remake.
