### ISSUE TITLE
Merge request for debianization

### ISSUE THREAD

**Issue by dkogan** [rocky/remake#33]
Hi. I updated and pushed the remake debian package to the debian repo:

    https://tracker.debian.org/news/788381

I'm co-maintaining the package with Yaroslav. The corresponding git branches live in your repository, so could you please fast-forward your debian and master-dfsg branches to those from my fork:

    https://github.com/dkogan/remake

I'd make a pull request, but those create ugly extra merge commits that I'd like to avoid (it does a 'git merge --no-ff').

Thanks

**Comment by rocky** [comment]
Not sure I understand the concern, but Debian branch pulled now. 

Thanks for updating the debian repo. I'm glad you are maintaining the package now.

**Comment by rocky** [comment]
BTW I've removed the debian files from the master branch and these are now back only in the debian branch.

Also, the relevant patches from Debian have been incorporated into master. 

If you want to commit directly to this repo, let me know.

**Comment by dkogan** [comment]
R. Bernstein <notifications@github.com> writes:

> Also, the relevant patches from Debian have been incorporated into
> master.

OK. Do note that the ar stuff is meant to handle a new-ish default
setting for ar shipped in debian, so MAYBE it's not appropriate for
other distros.


> If you want to commit directly to this repo, let me know.

That would be great. I would only touch the debian and master-dfsg
branches, and I'd push a tag for each release.

dima

**Comment by rocky** [comment]
dima reports:

> Do note that the ar stuff is meant to handle a new-ish default setting for ar shipped in debian, so MAYBE it's not appropriate for other distros.

I've disabled the feature tests for now.  As I understand it this is just testing order and doesn't have a semantic change for users.

> That would be great.

Request sent.  Yes, please update debian and master-dfsg as appropriate.


I've

**Comment by dkogan** [comment]
R. Bernstein <notifications@github.com> writes:

> Request sent. Yes, please update debian and master-dfsg as
> appropriate.

Done. We're now up-to-date until the next release. Thanks.
