### ISSUE TITLE
Errors running ./configure

### ISSUE THREAD

**Issue by IeiuniumLux** [rocky/remake#36]
I'm probably doing something wrong or missing bits, but I'm getting these errors when run autoconf and later ./configure on Ubuntu 16.04 LTS

-----------------------------
safe50@safe50-nuc2:~/Downloads/remake-release-remake-4.2.1-dbg-1.4$ sudo autoconf
configure.ac:33: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:34: error: possibly undefined macro: AM_MAINTAINER_MODE
configure.ac:52: error: possibly undefined macro: AM_PROG_AR
configure.ac:60: error: possibly undefined macro: AM_MISSING_PROG
configure.ac:63: error: possibly undefined macro: AM_GNU_GETTEXT_VERSION
configure.ac:64: error: possibly undefined macro: AM_GNU_GETTEXT
configure.ac:83: error: possibly undefined macro: AM_PROG_CC_C_O
configure.ac:95: error: possibly undefined macro: AC_STRUCT_ST_MTIM_NSEC
configure.ac:122: error: possibly undefined macro: pds_AC_DOS_PATHS
configure.ac:195: error: possibly undefined macro: AM_CONDITIONAL
configure.ac:565: error: possibly undefined macro: AM_WITH_DMALLOC
safe50@safe50-nuc2:~/Downloads/remake-release-remake-4.2.1-dbg-1.4$ ls con*config.h.W32.template  config.log  configure  configure.ac  configure.bat

config:
ar-lib        dospaths.m4  intlmacosx.m4  longlong.m4  missing      texinfo.tex
compile       gettext.m4   lib-ld.m4      Makefile.am  nls.m4
config.rpath  iconv.m4     lib-link.m4    Makefile.in  po.m4
depcomp       install-sh   lib-prefix.m4  mdate-sh     progtest.m4
safe50@safe50-nuc2:~/Downloads/remake-release-remake-4.2.1-dbg-1.4$ ./configure
./configure: line 2358: syntax error near unexpected token `subdir-objects'
./configure: line 2358: `AM_INIT_AUTOMAKE(subdir-objects 1.14 silent-rules foreign -Wall)'

**Comment by rocky** [comment]
(Re-)read https://github.com/rocky/remake/blob/remake-4-2/INSTALL-from-source.md and if that doesn't work then save the entire console of commands you entered and what was reported.

**Comment by IeiuniumLux** [comment]
Building fails when I run make.  Here is the entire console of commands I entered and what was reported.
----------------------------------------
safe50@safe50-nuc2:~/Downloads/remake-release-remake-4.2.1-dbg-1.4$ [ ! -f ./configure ] && autoreconf -f -i
Makefile.am:293: warning: '%'-style pattern rules are a GNU make extension
Makefile.am:170: warning: user target 'make$(EXEEXT)' defined here ...
/usr/share/automake-1.15/am/program.am: ... overrides Automake target 'make$(EXEEXT)' defined here
Makefile.am:38:   while processing program 'make'
doc/Makefile.am: warning: Oops!
doc/Makefile.am:     It appears this file (or files included by it) are triggering
doc/Makefile.am:     an undocumented, soon-to-be-removed automake hack.
doc/Makefile.am:     Future automake versions will no longer place in the builddir
doc/Makefile.am:     (rather than in the srcdir) the generated '.info' files that
doc/Makefile.am:     appear to be cleaned, by e.g. being listed in CLEANFILES or
doc/Makefile.am:     DISTCLEANFILES.
doc/Makefile.am:     If you want your '.info' files to be placed in the builddir
doc/Makefile.am:     rather than in the srcdir, you have to use the shiny new
doc/Makefile.am:     'info-in-builddir' automake option.
safe50@safe50-nuc2:~/Downloads/remake-release-remake-4.2.1-dbg-1.4$ ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) gcc3
checking for ranlib... ranlib
checking how to run the C preprocessor... gcc -E
checking whether ln -s works... yes
checking for ar... ar
checking for perl... perl
checking for ruby... ruby
checking for rspec... none
checking the archiver (ar) interface... ar
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for library containing strerror... none required
checking for a sed that does not truncate output... /bin/sed
checking whether NLS is requested... yes
checking for msgfmt... /usr/bin/msgfmt
checking for gmsgfmt... /usr/bin/msgfmt
checking for xgettext... /usr/bin/xgettext
checking for msgmerge... /usr/bin/msgmerge
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for shared library run path origin... done
checking for CFPreferencesCopyAppValue... no
checking for CFLocaleCopyCurrent... no
checking for GNU gettext in libc... yes
checking whether to use NLS... yes
checking where the gettext function comes from... libc
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking for library containing getpwnam... none required
checking for ANSI C header files... (cached) yes
checking for dirent.h that defines DIR... yes
checking for library containing opendir... none required
checking whether stat file-mode macros are broken... no
checking whether time.h and sys/time.h may both be included... yes
checking for stdlib.h... (cached) yes
checking locale.h usability... yes
checking locale.h presence... yes
checking for locale.h... yes
checking for unistd.h... (cached) yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking for string.h... (cached) yes
checking for memory.h... (cached) yes
checking sys/param.h usability... yes
checking sys/param.h presence... yes
checking for sys/param.h... yes
checking sys/resource.h usability... yes
checking sys/resource.h presence... yes
checking for sys/resource.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking sys/timeb.h usability... yes
checking sys/timeb.h presence... yes
checking for sys/timeb.h... yes
checking sys/select.h usability... yes
checking sys/select.h presence... yes
checking for sys/select.h... yes
checking sys/file.h usability... yes
checking sys/file.h presence... yes
checking for sys/file.h... yes
checking for an ANSI C-conforming const... yes
checking return type of signal handlers... void
checking for uid_t in sys/types.h... yes
checking for pid_t... yes
checking for off_t... yes
checking for size_t... yes
checking for ssize_t... yes
checking for unsigned long long int... yes
checking for uintmax_t... yes
checking for nanoseconds field of struct stat... st_mtim.tv_nsec
checking whether to use high resolution file timestamps... yes
checking for library containing clock_gettime... none required
checking whether system uses MSDOS-style paths... no
checking for standard gettimeofday... yes
checking for strdup... yes
checking for strndup... yes
checking for umask... yes
checking for mkstemp... yes
checking for mktemp... yes
checking for fdopen... yes
checking for fileno... yes
checking for dup... yes
checking for dup2... yes
checking for getcwd... yes
checking for realpath... yes
checking for sigsetmask... yes
checking for sigaction... yes
checking for getgroups... yes
checking for seteuid... yes
checking for setegid... yes
checking for setlinebuf... yes
checking for setreuid... yes
checking for setregid... yes
checking for getrlimit... yes
checking for setrlimit... yes
checking for setvbuf... yes
checking for pipe... yes
checking for strerror... yes
checking for strsignal... yes
checking for lstat... yes
checking for readlink... yes
checking for atexit... yes
checking for isatty... yes
checking for ttyname... yes
checking for pselect... yes
checking whether bsd_signal is declared... yes
checking vfork.h usability... no
checking vfork.h presence... no
checking for vfork.h... no
checking for fork... yes
checking for vfork... yes
checking for working fork... yes
checking for working vfork... (cached) yes
checking for strcasecmp... yes
checking for strncasecmp... yes
checking for strcmpi... no
checking for strncmpi... no
checking for stricmp... no
checking for strnicmp... no
checking for working strcoll... yes
checking for working alloca.h... yes
checking for alloca... yes
checking for vprintf... yes
checking for _doprnt... no
checking whether closedir returns void... no
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for GNU Guile... no
checking for getloadavg... yes
checking for pstat_getdynamic... no
checking for kstat_open in -lkstat... no
checking for getloadavg... yes
checking whether getloadavg requires setgid... no
checking whether sys_siglist is declared... yes
checking whether _sys_siglist is declared... yes
checking whether __sys_siglist is declared... no
checking for sys/wait.h... yes
checking for waitpid... yes
checking for wait3... yes
checking for union wait... no
checking if /bin/sh can be used to trace commands using -x... yes
checking readline/readline.h usability... yes
checking readline/readline.h presence... yes
checking for readline/readline.h... yes
./configure: line 10856: VL_LIB_READLINE: command not found
checking for tilde_expand() in <readline/readline.h>... no
checking for readline in -lreadline... yes
checking for history_list() in <readline/readline.h>... yes
checking for SA_RESTART... yes
checking whether dlopen is declared... yes
checking whether dlsym is declared... yes
checking whether dlerror is declared... yes
checking for library containing dlopen... -ldl
checking If the linker accepts -Wl,--export-dynamic... yes
checking for location of SCCS get command... get
checking if system libc has GNU glob... yes
checking if malloc debugging is wanted... no
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating glob/Makefile
config.status: creating po/Makefile.in
config.status: creating config/Makefile
config.status: creating doc/Makefile
config.status: creating unittest/Makefile
config.status: creating w32/Makefile
config.status: creating tests/config-flags.pm
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands
config.status: executing po-directories commands
config.status: creating po/POTFILES
config.status: creating po/Makefile
configure: Will install the 'make' binary under the name: remake
safe50@safe50-nuc2:~/Downloads/remake-release-remake-4.2.1-dbg-1.4$ make po-update
[ -d "po" ] && make do-po-update
make[1]: Entering directory '/home/safe50/Downloads/remake-release-remake-4.2.1-dbg-1.4'
tmppo="/tmp/po-remake-4.2.1+dbg-1.4.$$" \
  && rm -rf "$tmppo" \
  && mkdir "$tmppo" \
  && rsync -Lrtvz translationproject.org::tp/latest/make/  "$tmppo" \
  && cp "$tmppo"/*.po ./po \
  && rm -rf "$tmppo"
receiving incremental file list
./
be.po
cs.po
da.po
de.po
es.po
fi.po
fr.po
ga.po
gl.po
he.po
hr.po
id.po
it.po
ja.po
ko.po
lt.po
nl.po
pl.po
pt_BR.po
ru.po
sr.po
sv.po
tr.po
uk.po
vi.po
zh_CN.po
zh_TW.po

sent 540 bytes  received 434,806 bytes  96,743.56 bytes/sec
total size is 1,562,547  speedup is 3.59
cd po && make update-po
make[2]: Entering directory '/home/safe50/Downloads/remake-release-remake-4.2.1-dbg-1.4/po'
make remake.pot-update
make[3]: Entering directory '/home/safe50/Downloads/remake-release-remake-4.2.1-dbg-1.4/po'
sed -e '/^#/d' remove-potcdate.sin > t-remove-potcdate.sed
mv t-remove-potcdate.sed remove-potcdate.sed
package_gnu=""; \
test -n "$package_gnu" || { \
  if { if (LC_ALL=C find --version) 2>/dev/null | grep GNU >/dev/null; then \
	 LC_ALL=C find -L .. -maxdepth 1 -type f \
		       -size -10000000c -exec grep 'GNU remake' \
		       /dev/null '{}' ';' 2>/dev/null; \
       else \
	 LC_ALL=C grep 'GNU remake' ../* 2>/dev/null; \
       fi; \
     } | grep -v 'libtool:' >/dev/null; then \
     package_gnu=yes; \
   else \
     package_gnu=no; \
   fi; \
}; \
if test "$package_gnu" = "yes"; then \
  package_prefix='GNU '; \
else \
  package_prefix=''; \
fi; \
if test -n 'bug-make@gnu.org' || test 'https://github.com/rocky/remake/issues' = '@'PACKAGE_BUGREPORT'@'; then \
  msgid_bugs_address='bug-make@gnu.org'; \
else \
  msgid_bugs_address='https://github.com/rocky/remake/issues'; \
fi; \
case `/usr/bin/xgettext --version | sed 1q | sed -e 's,^[^0-9]*,,'` in \
  '' | 0.[0-9] | 0.[0-9].* | 0.1[0-5] | 0.1[0-5].* | 0.16 | 0.16.[0-1]*) \
    /usr/bin/xgettext --default-domain=remake --directory=.. \
      --add-comments=TRANSLATORS: --keyword=_ --keyword=N_  \
      --files-from=./POTFILES.in \
      --copyright-holder='Free Software Foundation, Inc.' \
      --msgid-bugs-address="$msgid_bugs_address" \
    ;; \
  *) \
    /usr/bin/xgettext --default-domain=remake --directory=.. \
      --add-comments=TRANSLATORS: --keyword=_ --keyword=N_  \
      --files-from=./POTFILES.in \
      --copyright-holder='Free Software Foundation, Inc.' \
      --package-name="${package_prefix}remake" \
      --package-version='4.2.1+dbg-1.4' \
      --msgid-bugs-address="$msgid_bugs_address" \
    ;; \
esac
dir.c:1088: warning: Although being used in a format string position, the msgid is not a valid C format string. Reason: In the directive number 3, the character 'I' is not a valid conversion specifier.
dir.c:1125: warning: Although being used in a format string position, the msgid is not a valid C format string. Reason: In the directive number 3, the character 'I' is not a valid conversion specifier.
test ! -f remake.po || { \
  if test -f ./remake.pot; then \
    sed -f remove-potcdate.sed < ./remake.pot > remake.1po && \
    sed -f remove-potcdate.sed < remake.po > remake.2po && \
    if cmp remake.1po remake.2po >/dev/null 2>&1; then \
      rm -f remake.1po remake.2po remake.po; \
    else \
      rm -f remake.1po remake.2po ./remake.pot && \
      mv remake.po ./remake.pot; \
    fi; \
  else \
    mv remake.po ./remake.pot; \
  fi; \
}
make[3]: Leaving directory '/home/safe50/Downloads/remake-release-remake-4.2.1-dbg-1.4/po'
test -z "be.po-update cs.po-update da.po-update de.po-update es.po-update fi.po-update fr.po-update ga.po-update gl.po-update he.po-update hr.po-update id.po-update it.po-update ja.po-update ko.po-update lt.po-update nl.po-update pl.po-update pt_BR.po-update ru.po-update sv.po-update tr.po-update uk.po-update vi.po-update zh_CN.po-update" || make be.po-update cs.po-update da.po-update de.po-update es.po-update fi.po-update fr.po-update ga.po-update gl.po-update he.po-update hr.po-update id.po-update it.po-update ja.po-update ko.po-update lt.po-update nl.po-update pl.po-update pt_BR.po-update ru.po-update sv.po-update tr.po-update uk.po-update vi.po-update zh_CN.po-update
make[3]: Entering directory '/home/safe50/Downloads/remake-release-remake-4.2.1-dbg-1.4/po'
be:
msgmerge  --lang=be be.po remake.pot -o be.new.po
......................................................................................................................................................................... done.
cs:
msgmerge  --lang=cs cs.po remake.pot -o cs.new.po
....................................................................................................... done.
da:
msgmerge  --lang=da da.po remake.pot -o da.new.po
......................................................................................................... done.
de:
msgmerge  --lang=de de.po remake.pot -o de.new.po
............................................................................................................. done.
es:
msgmerge  --lang=es es.po remake.pot -o es.new.po
........................................................................................................ done.
fi:
msgmerge  --lang=fi fi.po remake.pot -o fi.new.po
....................................................................................................... done.
fr:
msgmerge  --lang=fr fr.po remake.pot -o fr.new.po
.................................................................................................... done.
ga:
msgmerge  --lang=ga ga.po remake.pot -o ga.new.po
........................................................................................................ done.
gl:
msgmerge  --lang=gl gl.po remake.pot -o gl.new.po
.................................................................................................................................................................................................................................... done.
he:
msgmerge  --lang=he he.po remake.pot -o he.new.po
......................................................................................................................................................................................................................................................................................... done.
hr:
msgmerge  --lang=hr hr.po remake.pot -o hr.new.po
....................................................................................................... done.
id:
msgmerge  --lang=id id.po remake.pot -o id.new.po
............................................................................................................................. done.
it:
msgmerge  --lang=it it.po remake.pot -o it.new.po
............................................................................................................................ done.
ja:
msgmerge  --lang=ja ja.po remake.pot -o ja.new.po
....................................................................................................... done.
ko:
msgmerge  --lang=ko ko.po remake.pot -o ko.new.po
.................................................................................................... done.
lt:
msgmerge  --lang=lt lt.po remake.pot -o lt.new.po
................................................................................................................................................................................... done.
nl:
msgmerge  --lang=nl nl.po remake.pot -o nl.new.po
..................................................................................................... done.
pl:
msgmerge  --lang=pl pl.po remake.pot -o pl.new.po
...................................................................................................... done.
pt_BR:
msgmerge  --lang=pt_BR pt_BR.po remake.pot -o pt_BR.new.po
...................................................................................................... done.
ru:
msgmerge  --lang=ru ru.po remake.pot -o ru.new.po
..................................................................................................... done.
sv:
msgmerge  --lang=sv sv.po remake.pot -o sv.new.po
...................................................................................................... done.
tr:
msgmerge  --lang=tr tr.po remake.pot -o tr.new.po
................................................................................................................................................................................................................................................................................ done.
uk:
msgmerge  --lang=uk uk.po remake.pot -o uk.new.po
.......................................................................................................... done.
vi:
msgmerge  --lang=vi vi.po remake.pot -o vi.new.po
........................................................................................................ done.
zh_CN:
msgmerge  --lang=zh_CN zh_CN.po remake.pot -o zh_CN.new.po
........................................................................................................... done.
make[3]: Leaving directory '/home/safe50/Downloads/remake-release-remake-4.2.1-dbg-1.4/po'
make update-gmo
make[3]: Entering directory '/home/safe50/Downloads/remake-release-remake-4.2.1-dbg-1.4/po'
rm -f be.gmo && /usr/bin/msgfmt -c --statistics --verbose -o be.gmo be.po
be.po: 82 translated messages, 93 fuzzy translations, 398 untranslated messages.
rm -f cs.gmo && /usr/bin/msgfmt -c --statistics --verbose -o cs.gmo cs.po
cs.po: 411 translated messages, 40 fuzzy translations, 122 untranslated messages.
rm -f da.gmo && /usr/bin/msgfmt -c --statistics --verbose -o da.gmo da.po
da.po: 412 translated messages, 39 fuzzy translations, 122 untranslated messages.
rm -f de.gmo && /usr/bin/msgfmt -c --statistics --verbose -o de.gmo de.po
de.po: 412 translated messages, 39 fuzzy translations, 122 untranslated messages.
rm -f es.gmo && /usr/bin/msgfmt -c --statistics --verbose -o es.gmo es.po
es.po: 411 translated messages, 40 fuzzy translations, 122 untranslated messages.
rm -f fi.gmo && /usr/bin/msgfmt -c --statistics --verbose -o fi.gmo fi.po
fi.po: 320 translated messages, 84 fuzzy translations, 169 untranslated messages.
rm -f fr.gmo && /usr/bin/msgfmt -c --statistics --verbose -o fr.gmo fr.po
fr.po: 412 translated messages, 39 fuzzy translations, 122 untranslated messages.
rm -f ga.gmo && /usr/bin/msgfmt -c --statistics --verbose -o ga.gmo ga.po
ga.po: 412 translated messages, 39 fuzzy translations, 122 untranslated messages.
rm -f gl.gmo && /usr/bin/msgfmt -c --statistics --verbose -o gl.gmo gl.po
gl.po: 222 translated messages, 161 fuzzy translations, 190 untranslated messages.
rm -f he.gmo && /usr/bin/msgfmt -c --statistics --verbose -o he.gmo he.po
he.po: 155 translated messages, 210 fuzzy translations, 208 untranslated messages.
rm -f hr.gmo && /usr/bin/msgfmt -c --statistics --verbose -o hr.gmo hr.po
hr.po: 412 translated messages, 39 fuzzy translations, 122 untranslated messages.
rm -f id.gmo && /usr/bin/msgfmt -c --statistics --verbose -o id.gmo id.po
id.po: 390 translated messages, 60 fuzzy translations, 123 untranslated messages.
rm -f it.gmo && /usr/bin/msgfmt -c --statistics --verbose -o it.gmo it.po
it.po: 389 translated messages, 61 fuzzy translations, 123 untranslated messages.
rm -f ja.gmo && /usr/bin/msgfmt -c --statistics --verbose -o ja.gmo ja.po
ja.po: 412 translated messages, 39 fuzzy translations, 122 untranslated messages.
rm -f ko.gmo && /usr/bin/msgfmt -c --statistics --verbose -o ko.gmo ko.po
ko.po: 411 translated messages, 39 fuzzy translations, 123 untranslated messages.
rm -f lt.gmo && /usr/bin/msgfmt -c --statistics --verbose -o lt.gmo lt.po
lt.po: 104 translated messages, 123 fuzzy translations, 346 untranslated messages.
rm -f nl.gmo && /usr/bin/msgfmt -c --statistics --verbose -o nl.gmo nl.po
nl.po: 411 translated messages, 40 fuzzy translations, 122 untranslated messages.
rm -f pl.gmo && /usr/bin/msgfmt -c --statistics --verbose -o pl.gmo pl.po
pl.po: 411 translated messages, 39 fuzzy translations, 123 untranslated messages.
rm -f pt_BR.gmo && /usr/bin/msgfmt -c --statistics --verbose -o pt_BR.gmo pt_BR.po
pt_BR.po: 412 translated messages, 39 fuzzy translations, 122 untranslated messages.
rm -f ru.gmo && /usr/bin/msgfmt -c --statistics --verbose -o ru.gmo ru.po
ru.po: 411 translated messages, 40 fuzzy translations, 122 untranslated messages.
rm -f sv.gmo && /usr/bin/msgfmt -c --statistics --verbose -o sv.gmo sv.po
sv.po: 411 translated messages, 39 fuzzy translations, 123 untranslated messages.
rm -f tr.gmo && /usr/bin/msgfmt -c --statistics --verbose -o tr.gmo tr.po
tr.po: 212 translated messages, 205 fuzzy translations, 156 untranslated messages.
rm -f uk.gmo && /usr/bin/msgfmt -c --statistics --verbose -o uk.gmo uk.po
uk.po: 411 translated messages, 40 fuzzy translations, 122 untranslated messages.
rm -f vi.gmo && /usr/bin/msgfmt -c --statistics --verbose -o vi.gmo vi.po
vi.po: 411 translated messages, 40 fuzzy translations, 122 untranslated messages.
rm -f zh_CN.gmo && /usr/bin/msgfmt -c --statistics --verbose -o zh_CN.gmo zh_CN.po
zh_CN.po: 407 translated messages, 44 fuzzy translations, 122 untranslated messages.
make[3]: Leaving directory '/home/safe50/Downloads/remake-release-remake-4.2.1-dbg-1.4/po'
make[2]: Leaving directory '/home/safe50/Downloads/remake-release-remake-4.2.1-dbg-1.4/po'
make po-check
make[2]: Entering directory '/home/safe50/Downloads/remake-release-remake-4.2.1-dbg-1.4'
if test -f po/POTFILES.in; then \
  grep '^[^#]' po/POTFILES.in | sort > po-check-1; \
  perl -wn -e 'if (/\b_\(/) { $ARGV eq "./makeint.h" || print "$ARGV\n" and close ARGV }' `find . -name '*.[ch]'` | sed 's,^\./,,' | sort > po-check-2; \
  diff -u po-check-1 po-check-2 || exit 1; \
  rm -f po-check-1 po-check-2; \
fi
make[2]: Leaving directory '/home/safe50/Downloads/remake-release-remake-4.2.1-dbg-1.4'
make[1]: Leaving directory '/home/safe50/Downloads/remake-release-remake-4.2.1-dbg-1.4'
safe50@safe50-nuc2:~/Downloads/remake-release-remake-4.2.1-dbg-1.4$ make
make  all-recursive
make[1]: Entering directory '/home/safe50/Downloads/remake-release-remake-4.2.1-dbg-1.4'
Making all in glob
make[2]: Entering directory '/home/safe50/Downloads/remake-release-remake-4.2.1-dbg-1.4/glob'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/safe50/Downloads/remake-release-remake-4.2.1-dbg-1.4/glob'
Making all in config
make[2]: Entering directory '/home/safe50/Downloads/remake-release-remake-4.2.1-dbg-1.4/config'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/safe50/Downloads/remake-release-remake-4.2.1-dbg-1.4/config'
Making all in po
make[2]: Entering directory '/home/safe50/Downloads/remake-release-remake-4.2.1-dbg-1.4/po'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/safe50/Downloads/remake-release-remake-4.2.1-dbg-1.4/po'
Making all in doc
make[2]: Entering directory '/home/safe50/Downloads/remake-release-remake-4.2.1-dbg-1.4/doc'
make[2]: *** No rule to make target 'fdl.texi', needed by 'make.info'.  Stop.
make[2]: Leaving directory '/home/safe50/Downloads/remake-release-remake-4.2.1-dbg-1.4/doc'
Makefile:916: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/safe50/Downloads/remake-release-remake-4.2.1-dbg-1.4'
Makefile:621: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by rocky** [comment]
This is a different failure from before. For you for now,  in that last command just run `make -k` and ignore the errors in building the doc.  Or copy a fdl.texi from one of the tarballs. 

After remake is build, if you want to track down what's going on with that failure, you can use remake to help you out.

**Comment by IeiuniumLux** [comment]
Copy that.  Thanks!
