### ISSUE TITLE
--verbosity usage (--help) message does not match behavior

### ISSUE THREAD

**Issue by marvingreenberg** [rocky/remake#39]
According to the usage message:

      --verbosity[=LEVEL]         Set verbosity level. LEVEL may be "terse" "no-header" or
                              "full". The default is "full".

But LEVEL is actually required.

    $ remake -C Somedir --verbosity
    remake: option `--verbosity' requires an argument

    $ remake --verbosity -C Somedir 
    remake: Nothing to be done for 'Somedir'

The latter example demonstrates that --verbosity consumes the next argument as a LEVEL without any warning of the validity of the level and in spite of the fact that it is an argument option.

**Comment by rocky** [comment]
Thanks for the bug report. I've changed the --help message. But since I make lots of mistakes (and that is partly why I added a full debugger to remake), please double check.
