### ISSUE TITLE
Rsync fails from behind firewall

### ISSUE THREAD

**Issue by psmoot** [rocky/remake#43]
I was trying to build remake from behind a corporate firewall. Our firewall blocks rsync connections but allows wget. As a result, I could not update the po/*.po files.

The translationproject.org site recommends using wget instead. I would like to modify maintMakefile to use wget so as to be more firewall friendly.

**Comment by rocky** [comment]
That make sense. Since you are in the best position to test this, make the change and open a PR. Thanks.
