### ISSUE TITLE
Internet access is required to build

### ISSUE THREAD

**Issue by xyzzyz** [rocky/remake#46]
I ran autogen.sh script from remake-release-remake-4.2.1-dbg-1.4 release. It broke on:

`
[ -d "po" ] && make do-po-update
make[1]: Entering directory `/home/amichalik/tmp/remake-release-remake-4.2.1-dbg-1.4'
Makefile:1927: warning: overriding recipe for target `ChangeLog'
Makefile:1594: warning: ignoring old recipe for target `ChangeLog'
tmppo="/tmp/po-remake-4.2.1+dbg-1.4.$$" \
  && rm -rf "$tmppo" \
  && mkdir "$tmppo" \
  && rsync -Lrtvz translationproject.org::tp/latest/make/  "$tmppo" \
  && cp "$tmppo"/*.po ./po \
  && rm -rf "$tmppo"
rsync: failed to connect to translationproject.org (2a01:7c8:c037:6::20): Connection timed out (110)
rsync: failed to connect to translationproject.org (80.69.83.146): Network is unreachable (101)
rsync error: error in socket IO (code 10) at clientserver.c(125) [Receiver=3.1.2]
make[1]: *** [do-po-update] Error 10
`

Build system should never require internet connection and download random packages. If dependencies are required, they either should be packaged alongside release, or clearly described (e.g. the build will fail in case GNU Readline is not available, but it won't try to download and install it on its own).

**Comment by rocky** [comment]
When you build a development system, often there are additional requirements. 

If this is a problem, use released sources.

**Comment by xyzzyz** [comment]
These are released sources, e.g. https://github.com/rocky/remake/archive/release-remake-4.2.1+dbg-1.4.tar.gz . If by "released sources" you mean something else than a tarball that's named "release" you obtain by visiting a "Releases" page, please let me know.

**Comment by rocky** [comment]
Use the files from https://sourceforge.net/projects/bashdb/files/remake/4.2%2Bdbg-1.4/ and you'll be fine.  I don't see how to remove those github-related files short of removing the release tag.
