### ISSUE TITLE
Is profiling working?

### ISSUE THREAD

**Issue by jeffsaremi** [rocky/remake#48]
I download 4.2.1 and built on ubuntu 16.04
Then i pointed that to our makefile, the top level target, and asked it to profile; like so:
```
remake --profile -C dir/ -f Makefile all
```
The whole thing took one hour since we have too many targets to build. At the end of that I get a file called `callgrind.out.193121`
This is the entire contents of the callgrind file:

```
$ cat callgrind.out.193121
version: 1
creator: remake 4.2.1+dbg-1.4
cmd: remake --profile -C aris -f Makefile all
pid: 193121

desc: Trigger: Normal program termination
desc: Node: Targets

positions: line
events: 100usec
summary: 25644383


```

Am I missing something? Has Profiling been redefined?
Is Remake able to capture timings for all targets being invoked in the entire DAG for a makefile?

**Comment by rocky** [comment]
As far as I can tell, yes.  I just ran the profile on the remake-4-2 branch in github: 

```
$ remake --profile -C . -f Makefile all
remake: Entering directory 'remake'
Makefile:2048: warning: overriding recipe for target 'ChangeLog'
...
Created callgrind profiling data file: callgrind.out.12981
remake[2]: Entering directory 'remake'
Makefile:2048: warning: overriding recipe for target 'ChangeLog'
Makefile:1720: warning: ignoring old recipe for target 'ChangeLog'
remake[2]: Leaving directory 'remake'
Created callgrind profiling data file: callgrind.out.12982
remake[1]: Leaving directory 'remake'
Created callgrind profiling data file: callgrind.out.12966
remake: Leaving directory 'remake'
Created callgrind profiling data file: callgrind.out.12963
$ ls callgrind*
callgrind.out.12963  callgrind.out.12966  callgrind.out.12982
$ wc callgrind*
  214   253  2196 callgrind.out.12963
  182   214  1886 callgrind.out.12966
 3316  3760 48620 callgrind.out.12982
 3712  4227 52702 total
```

See if that works for you as well. 

> Is Remake able to capture timings for all targets being invoked in the entire DAG for a makefile?

As far as I know, yes. If you have reason to believe otherwise, then create a _small_ test case that shows the problem more convincingly. 

And of course, since this is open source code, you have all the resources at your disposal to isolate and fix bugs.

**Comment by jeffsaremi** [comment]
So this should generate one callgrind file for each target?
I only get one for the 100's of targets that are eventually called.
I'll work on getting a test case prepared. thanks

**Comment by rocky** [comment]
Closing for lack of interest.
