### ISSUE TITLE
Feature: allow searching parent directory for a Makefile.

### ISSUE THREAD

**Issue by rocky** [rocky/remake#69]
I think a cool feature to add is that if no Makefile appears in the current directory the parent directory is searched (using that directory as the cwd) and so on. 

This is the way many other more modern tools work, e.g. git, pyenv.

**Comment by rocky** [comment]
Is in `remake-4-3` branch now.

Backport to `remake-4-2` ?

**Comment by boretom** [comment]
In your experience how fast is the adoption rate for a new version?

And checking the changes necessary for this feature it seems not too much has to be added. Would seem to be worth it, I think.

**Comment by rocky** [comment]
> In your experience how fast is the adoption rate for a new version?

What has happened in the past is that some incident triggers off this explosion of interest. JetBrains adopts a library I've written, someone puts out a hackernews post, or a distro decides to include a package.

The way I  find out about it is that all of a sudden there are lots of bug reports. Or some meter shoots up. 

Had this been done earlier, it might have gotten into then next Ubuntu 20.04 release. (I think zshdb 1.1.2 will be in that release). 

I think there's still a good chance for that if the GNU Make 4.3 speedup is as expected, having that _and_ profiling will be of importance. 

But personally, I really like the `-c` option. 

Or nothing may come of this.

**Comment by rocky** [comment]
With the recent releases, all of this is done and out.
