### ISSUE TITLE
Undefined references

### ISSUE THREAD

**Issue by SivaprasadAddepalli** [rocky/remake#7]
Hi,

I tried to install remake on our linux machines, but it failed with the below error messages:

gcc  -g -O2   -o make ar.o arscan.o commands.o default.o dir.o expand.o file.o function.o getopt.o getopt1.o implicit.o job.o main.o misc.o read.o remake.o remote-stub.o rule.o signame.o strcache.o variable.o version.o vpath.o hash.o buildargv.o debug.o print.o trace.o break.o cmd.o fns.o file2line.o msg.o stack.o   -lrt 
cmd.o: In function `enter_debugger':
/home/xsivaad/Downloads/remake-3.82+dbg-0.6/debugger/cmd.c:496: undefined reference to`add_history'
/home/xsivaad/Downloads/remake-3.82+dbg-0.6/debugger/cmd.c:497: undefined reference to `execute_line'
/home/xsivaad/Downloads/remake-3.82+dbg-0.6/debugger/cmd.c:499: undefined reference to`add_history'
/home/xsivaad/Downloads/remake-3.82+dbg-0.6/debugger/cmd.c:500: undefined reference to `dbg_cmd_step'
/home/xsivaad/Downloads/remake-3.82+dbg-0.6/debugger/cmd.c:504: undefined reference to`dbg_cmd_quit'
/home/xsivaad/Downloads/remake-3.82+dbg-0.6/debugger/cmd.c:403: undefined reference to `cmd_initialize'
collect2: ld returned 1 exit status
make[1]: *** [make] Error 1
make[1]: Leaving directory`/home/xsivaad/Downloads/remake-3.82+dbg-0.6'
make: **\* [check-recursive] Error 1

**Comment by rileyrg** [comment]
> Hi,
> 
> I tried to install remake on our linux machines, but it failed with the below error messages:
> 
> gcc -g -O2 -o make ar.o arscan.o commands.o default.o dir.o expand.o file.o function.o getopt.o getopt1.o implicit.o job.o main.o misc.o read.o remake.o remote-stub.o rule.o signame.o strcache.o variable.o version.o vpath.o hash.o buildargv.o debug.o print.o trace.o break.o cmd.o fns.o file2line.o msg.o stack.o -lrt
> cmd.o: In function `enter_debugger': /home/xsivaad/Downloads/remake-3.82+dbg-0.6/debugger/cmd.c:496: undefined reference to`add_history'
> /home/xsivaad/Downloads/remake-3.82+dbg-0.6/debugger/cmd.c:497: undefined reference to `execute_line' /home/xsivaad/Downloads/remake-3.82+dbg-0.6/debugger/cmd.c:499: undefined reference to`add_history'
> /home/xsivaad/Downloads/remake-3.82+dbg-0.6/debugger/cmd.c:500: undefined reference to `dbg_cmd_step' /home/xsivaad/Downloads/remake-3.82+dbg-0.6/debugger/cmd.c:504: undefined reference to`dbg_cmd_quit'
> /home/xsivaad/Downloads/remake-3.82+dbg-0.6/debugger/cmd.c:403: undefined reference to `cmd_initialize' collect2: ld returned 1 exit status make[1]: *** [make] Error 1 make[1]: Leaving directory`/home/xsivaad/Downloads/remake-3.82+dbg-0.6'
> make: *** [check-recursive] Error 1

Debian testing/Bullseye. Also can't install with the same errors.  remake-4.3+dbg-1.5.

I was looking for "bashdb" btw which is removed from the debian packages.

Package "remake" is in the repos however.

**Comment by rocky** [comment]
With respect to your make build your local environment is not set up properly for the build to find GNU readline's history. 

With respect to bashdb, open source is only as good as those willing to work and maintain it. Debian needs a bashdb maintainer. Hey, how about you? 

Finally finding some issue and appending to it stuff that comes into you head isn't good net etiquette.
